name: ci
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y meson libjsoncpp-dev

    - name: Build
      run: |
        meson build
        ninja -C build

    - name: Run
      run: |
        ./build/vmtest-action-demo
