name: ci
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    strategy:
      matrix:
        - name: v6.0
          url: https://github.com/danobi/vmtest/releases/download/test_assets/bzImage-v6.0
        - name: v6.1
          url: https://github.com/danobi/vmtest/releases/download/test_assets/bzImage-v6.1
        - name: v6.2
          url: https://github.com/danobi/vmtest/releases/download/test_assets/bzImage-v6.2

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y meson libjsoncpp-dev

    - name: Build
      run: |
        meson build
        ninja -C build

    - name: Run
      uses: danobi/vmtest-action@master
      with:
        name: ${{ matrix.name }}
        kernel_url: ${{ matrix.url }}
        command: ${{ github.workspace}}/build/vmtest-action-demo
